(function(){if(this.zone)return console.log("Zone already has been defined"),this.zone;var w={},f=function(a,b){if(!(a.length>=b))throw Error("Expected at least "+b+" arguments, but got "+a.length);},m=function(a,b,c){f(a,b);if(!(a.length<=c))throw Error("Expected at most "+c+" arguments, but got "+a.length);},A=function(a,b){return""===a?b:a+"."+b},r=Array.isArray;r||(r=function(a){return 0<=a.length});var B=function(a){if("function"!==typeof a)throw Error("Not a function: "+a);a=a.toString();var b=
a.match(/^\s*function\s*(?:\w*\s*)?\(([\s\S]*?)\)/),b=b?b[1]?b[1].trim().split(/\s*,\s*/):[]:null;null===b&&console.log("Failed to parse the function (perhaps it is too long?) : "+a);return b},d=function(a,b,c){this.__children={};this.__parent=b;this.__imports=c;this.__sealed=!1;this.__values={};this.__interceptors={};this.__fullName=a;if(b){if(b.__children[a])throw Error("Module "+this.__fullName+" already contains a module "+a);this.__fullName=A(b.__fullName,a);b.__children[a]=this}w[this.__fullName]=
this},s=new d("",null,[]),G=function(a,b){if(a===b)return 2;for(;a&&a!==b;)a=a.__parent;return null===a?0:1},C=function(a){if(a.__sealed)throw Error("Module "+a.__fullName+" is sealed");},t=function(a,b){var c=w[a],e,g,d,c=c||null;if(!c&&b)for(e=a.split(/\./),c=s,g=0,d=e.length;g<d;++g)c=c.create(e[g],null);return c},D=function(a,b){var c=B(b);if(null!==c&&c.length!==a.length)throw Error("Formals and parameter names do not match");},n=function(a){var b;this.isConstructor=!1;if(1===a.length&&r(a[0]))b=
a[0].length,this.names=a[0].slice(0,b-1),this.func=a[0][b-1],D(this.names,this.func);else if(2===a.length)this.names=a[0].slice(),this.func=a[1],D(this.names,this.func);else if("function"===typeof a[0]){if(this.func=a[0],this.names=B(this.func),null===this.names)throw Error("Failed to determine function signature");}else throw Error("Invalid function description");},H=function(a,b){this.module=a;this.descriptor=b},u=function(a){this.value=a},p=function(a){return a instanceof u?a:new u(a)},l=function(a){return a instanceof
n?a:1===a.length&&a[0]instanceof n?a[0]:new n(a)},v=function(a){a=l(a);a.isConstructor=!0;return a},E=function(a,b,c,e){this.module=a;this.name=b;this.fullName=A(a.__fullName,b);this.descriptor=e;this.resolving=!1;switch(c){case 0:case 2:case 1:this.access=c;break;default:throw Error("Invalid access "+c);}};E.prototype.isAccessible=function(a){return this.access<=a};var h=function(a,b,c,e){m(e,1,2);if(0===b.length||0<=b.indexOf("."))throw Error("Invalid name to bind "+b);if(a.__values[b])throw Error("Name "+
b+" already bound in "+a.__fullName);C(a);e=e instanceof u||e instanceof n?e:1!==e.length||"function"===typeof e[0]||e[0]instanceof n?l(e):p(e[0]);c=new E(a,b,c,e);a.__values[b]=c;return a},x=function(a,b){this.module=b;this.local=a;this.modulePath=".";var c;c=a.lastIndexOf(".");0<=c&&(this.modulePath=a.substring(0,c),this.module=t(this.modulePath,!1),this.local=a.substr(c+1))},y=function(a,b,c,e){var g,d,f,h,k;f=new x(a,b);a=f.module;f=f.local;a!==b&&(c=Math.min(c,G(b,a)));e=e||{};for(b=null;!b&&
a;){a.__sealed=!0;if((b=a.__values[f])&&b.isAccessible(c))break;b=null;if(!b){if(!0===e[a.__fullName])throw Error("Cyclic dependency : "+a.__fullName);try{for(e[a.__fullName]=!0,k=a.__imports||[],a.__imports=k,g=0,d=k.length;g<d&&!b;++g){h=t(k[g],!1);if(null===h)throw Error("Invalid dependency : "+k[g]);b=y(f,h,0,e)}}finally{e[a.__fullName]=!1}c=1;a=a.__parent}}return b},z=function(a,b,c,e){var g,d,f,h,k,q,l,m,n,p;n=c.names;p=c.func;f=c.isConstructor;h=[];k=[a];g=0;for(d=n.length;g<d;++g)if(q=n[g],
"#"===q[0]){if(!e)throw Error("Free arguments are not allowed");h.push(k.length);k.push(void 0)}else if(m=!1,"?"===q[0]&&(m=!0,q=q.substr(1)),c=y(q,a,b,{})){try{l=F(c)}catch(r){throw console.log("Injection failed: "+q),r;}k.push(l)}else if(m)k.push(void 0);else return console.log("Injectable not found: "+q),null;d=h.length;return function(){for(g=0;g<d;++g)k[h[g]]=arguments[g];var a=Function.prototype.bind.apply(p,k);return f?new a:a()}},F=function(a){var b,c,e,g,d,f;if(a.hasOwnProperty("value"))return a.value;
if(!0===a.resolving)throw Error("Cyclic dependency detected with "+a.fullName);a.resolving=!0;if(a.descriptor instanceof u)g=a.descriptor.value;else{try{try{b=z(a.module,2,a.descriptor,!1)}catch(h){throw console.log("Failed to resolve "+a.fullName),h;}if(null===b)throw console.log("Failed to resolve "+a.fullName),Error("Failed to resolve "+a.fullName);}finally{a.resolving=!1}try{g=b()}catch(k){throw Error("Failed to resolve "+a.fullName+"\n"+k.toString());}}b=a.module.__interceptors[a.name]||[];d=
0;for(f=b.length;d<f;++d){c=b[d];try{e=z(c.module,2,c.descriptor,!1)}catch(l){throw console.log("Interceptor for "+a.fullName+" failed"),l;}if(null===e)throw Error("Failed to resolve interceptor for "+a.name);g=e()(g)}a.value=g;delete a.descriptor;return a.value};d.prototype.inject=function(a){var b=l(arguments),b=z(this,0,b,!0);if(null===b)throw Error("Failed to create injected function");return b};d.prototype.create=function(a){var b;if(0===a.length||0<=a.indexOf("."))throw Error("Invalid name "+
a);(b=this.__children[a])||(b=new d(a,this,null));return b};d.prototype.configure=function(a){if(!r(a))throw Error("Imports are not an array");if(this.__imports)throw Error("Module has already been configured "+this.__fullName);C(this);this.__imports=a.slice();return this};d.prototype.get=function(a){var b=y(a,this,0,{});if(b)return F(b);throw Error("Not found "+a);};d.prototype.definePrivate=function(a,b){f(arguments,2);return h(this,a,2,Array.prototype.slice.call(arguments,1))};d.prototype.defineProtected=
function(a,b){f(arguments,2);return h(this,a,1,Array.prototype.slice.call(arguments,1))};d.prototype["export"]=function(a,b){f(arguments,2);return h(this,a,0,Array.prototype.slice.call(arguments,1))};d.prototype.factory=function(a,b){f(arguments,2);var c=l(Array.prototype.slice.call(arguments,1));return h(this,a,2,[c])};d.prototype.protectedFactory=function(a,b){f(arguments,2);var c=l(Array.prototype.slice.call(arguments,1));return h(this,a,1,[c])};d.prototype.service=function(a,b){f(arguments,2);
var c=v(Array.prototype.slice.call(arguments,1));return h(this,a,2,[c])};d.prototype.protectedService=function(a,b){f(arguments,2);var c=v(Array.prototype.slice.call(arguments,1));return h(this,a,1,[c])};d.prototype.interceptor=function(a,b){var c=new x(a,this),e=c.module;null===e&&(e=t(c.modulePath,!0));var d=Array.prototype.slice.call(arguments,1),d=l(d),d=new H(this,d),f=e.__interceptors[c.local];f||(e.__interceptors[c.local]=f=[]);f.push(d);return this};d.prototype.value=function(a,b){f(arguments,
2);var c=p(b);return h(this,a,2,[c])};d.prototype.protectedValue=function(a,b){f(arguments,2);var c=p(b);return h(this,a,1,[c])};d.prototype.exportFactory=function(a,b){f(arguments,2);var c=l(Array.prototype.slice.call(arguments,1));return h(this,a,0,[c])};d.prototype.exportService=function(a,b){f(arguments,2);var c=v(Array.prototype.slice.call(arguments,1));return h(this,a,0,[c])};d.prototype.exportValue=function(a,b){f(arguments,2);var c=p(b);return h(this,a,0,[c])};this.zone=function(a,b){if(!a)return s;
var c=t(a,!b);if(c)return c;throw Error("Module not found "+a);};this.zone.asFunction=function(a){m(arguments,1,2);return l(arguments)};this.zone.asConstructor=function(a){m(arguments,1,2);return v(arguments)};this.zone.asValue=function(a){m(arguments,1,1);return p(a)};this.zone.inject=function(a,b){m(arguments,1,3);var c="",d=arguments;"string"===typeof arguments[0]&&(c=a,d=Array.prototype.slice.call(d,1));var f=l(d);return function(){return zone(c,!0).inject(f).apply(null,arguments)}};this.zone.get=
function(a){m(arguments,1,1);var b=new x(a,s);if(null===b.module)throw Error("Not found "+a);return b.module.get(b.local)};this.zone.reset=function(){s=new d("",null,[]);w={}};this.zone.version=function(){return"1.0"};return this.zone}).call(this);
